#!/bin/bash

function getCurrentAppMac {
  
  # Detect locked screen
  python -c 'import sys,Quartz; d=Quartz.CGSessionCopyCurrentDictionary(); sys.exit(d and d.get("CGSSessionScreenIsLocked", 0) == 0 and d.get("kCGSSessionOnConsoleKey", 0) == 1)'
  if [ $? -eq 0 ]; then
    echo "idle"
    return
  fi
  
  # Detect screensaver
  osascript << EOF
    tell application "System Events"
      if exists process "ScreenSaverEngine"
        return "idle"
      end if
      return name of first application process whose frontmost is true
    end tell
EOF
}

function getCurrentApp() {
  if [[ $OSTYPE == darwin* ]]; then
    getCurrentAppMac
  else
    echo Unsupported OS: $OSTYPE
  fi
}

app=$(getCurrentApp)

if [ "$app" == "idle" ]; then
  exit 0
fi

dateAndTime=$(date +"%Y-%m-%d %H:%M:%S")
date=$(date +"%Y-%m-%d")

echo "$app"
echo "$dateAndTime $app" >> ~/Dropbox/System/hours/$date.log
